### ISSUE TITLE
Review #1 - Detalles en el diseño, form y redirección.

### ISSUE THREAD

**Issue by FacundoEG** [andycontreras/desafio-4#1]
Hola Andres! como estas?

Estoy revisando tu desafío y encontre algunas cositas que me gustaría mostrarte sobre el diseño!

Primero, en la parte de las cards de los servicios del index.html, al bajar mucho la resolución los parrafos se salen del contenedor de la card:

![Screenshot_20220116_102506](https://user-images.githubusercontent.com/79592789/149661861-8ba3d34c-3f46-43c6-98a5-67de1ee43854.png)

Segundo, cuando mando el form no me devuelve bien el nombre de la persona que lo envio:

![Screenshot_20220116_102807](https://user-images.githubusercontent.com/79592789/149661920-5273e8f3-99f6-4280-92cb-1861ecbd8956.png)

Ademas que me devuelve como un error cada vez que lo mando, sea lo que sea que ponga:

![Screenshot_20220116_102850](https://user-images.githubusercontent.com/79592789/149661961-ed336c53-dc12-4c0a-813b-945cdb9f6907.png)

Despues, cuando quiero volver al index del proyecto desde otra pagina me devuelve error:

![Screenshot_20220116_103139](https://user-images.githubusercontent.com/79592789/149662108-2117c5ba-f84a-43ad-85c9-9c58ae37f372.png)

Yo creo que hay un tema con el link para redireccionar, ya que busca home.html y la pagina principal es index.html

Finalmente en la parte de la page de portfolio, fijate que las cards no aguantan el cambio de resolución y se salen del viewport:

![Screenshot_20220116_103322](https://user-images.githubusercontent.com/79592789/149662214-8eef1287-2182-4c8c-896d-fcaf5ccd77d5.png)

Yo te diría que esto lo podes solucionar facil cambiando el breakpoint de la pagina para que cambie antes a mobile y pueda aguantar la resolución.

Te tendría que pedir que revises esas cositas si? mas que nada lo del form y la redirección de la pagina que son premisas de este desafío.

Cualquier cosita me podes consultar por aca o mismo en el canal de la carrera!

Saludos!

**Comment by andycontreras** [comment]
Hola facu, gracias por las aclaraciones y los consejos, ya solucioné lo del link que redirige a la pagina principal, se me habia olvidado cambiar eso antes de enviarlo, con respecto a lo la pagina de portfolio y lo que se salia del viewport era que en la clase .portfolio le tenia puesto un display: flex, lo eliminé y funcionó bien. Solo me falta ver bien lo del formulario de contacto, muchas gracias

**Comment by andycontreras** [comment]
Listo ya hice las modificaciones y ya lo envié

**Comment by FacundoEG** [comment]
Dale Andy ahi lo estuve viendo y mejoro todo!

Una cosita mas, estoy ahora revisando tu desafío y te queria mostrar otro error que me sale al cargar los scripts en el portfolio.

Fijate que me esta tirando este error porque la funcion addPortfolio() quiere cargar elementos del template cuando aun no se termino de cargar del todo la page:

![Screenshot_20220117_100920](https://user-images.githubusercontent.com/79592789/149774962-42fa51ac-d835-4eb3-8d15-c7e79acbb3f3.png)

Al parecer esto pasa porque el script que carga el js de la pagina no tiene definido el "defer" entonces quiere cargar todo antes de esperar a los demas scripts:

![Screenshot_20220117_101022](https://user-images.githubusercontent.com/79592789/149775094-ceebe774-bab1-4c99-9891-7e8ecf8e85cb.png)

Queres pegarle una ojeada rapido a esto y te dejo abierta la review asi despues te termino de dar el visto bueno cuando lo arregles? es una cosita chica nomas y prefiero que le pegues una ojeada y esperar asi termino de hacer la review

**Comment by FacundoEG** [comment]
Dale Andy ahi lo estuve viendo y mejoro todo!

Una cosita mas, estoy ahora revisando tu desafío y te queria mostrar otro error que me sale al cargar los scripts en el portfolio.

Fijate que me esta tirando este error porque la funcion addPortfolio() quiere cargar elementos del template cuando aun no se termino de cargar del toda la page:

![Screenshot_20220117_100920](https://user-images.githubusercontent.com/79592789/149774962-42fa51ac-d835-4eb3-8d15-c7e79acbb3f3.png)

Al parecer esto pasa porque el script que carga el js de la pagina no tiene definido el "defer" entonces quiere cargar todo antes de esperar a los demas scripts:

![Screenshot_20220117_101022](https://user-images.githubusercontent.com/79592789/149775094-ceebe774-bab1-4c99-9891-7e8ecf8e85cb.png)

Despues en la page de servicios parece que hay algun problema al querer cargar las cards, al parecer esto puede suceder por el orden en como se cargan los js y tambien a la hora de hacer referencia a los elementos.

Mas que nada estaria bueno chequear el orden de los eventos dentro de la función que trae los servicios.

![Screenshot_20220117_101928](https://user-images.githubusercontent.com/79592789/149776269-b021a9ae-397c-4ef3-84e3-8ff0a6c19f73.png)

Queres pegarle una ojeada a esto y te dejo abierta la review asi despues te termino de dar el visto bueno cuando lo arregles? 

Son detalles pero prefiero que le pegues una revisión y esperar asi termino de hacer la review, te parece?

De todas formas lo demas quedo todo re arreglado asi que yo creo que despues de esto ya lo veo aprobadisimo! 

Cualquier cosita me podes consultar por aca si?

**Comment by andycontreras** [comment]
Hola facu, segun yo anoche me cargo jajaa pero bueno puede fallar, ahora ando en el trabajo, en 5 horas salgo, me da chance de aalor llegar y verificar todo eso y hacer las correcciones?

**Comment by FacundoEG** [comment]
Es que a mi tambien me carga bien si recargo la pagina! pero al parecer sucede eventualmente, no siempre.

Si no te precupes! yo te lo digo para no tener que poner que necesitas ajustes, asi capaz aprovechas y directamente resolves eso y ya te doy el visto bueno.

No hagas problema, vos resolvelo tranqui que cuando este ya termino la review si?

**Comment by andycontreras** [comment]
Si no, igual bien que me pasen estas cosas para así en el futuro estar mas pendiente de esos detañles y de revisar bien el codigo. Dale muchas gracias Facu, al llegar a casa me pongo wn eso, mil gracias!

**Comment by andycontreras** [comment]
Hola Facu como estas? ya hice las modificaciones que me dijiste,  refresqué par de veces para comprobar que no arrojara el mismo error, y por ahora salió bien

**Comment by FacundoEG** [comment]
Andy ahi lo probe y funciona bien ahora! asi que te dejo el visto bueno y te cierro el issue! 

Felicitaciones y exitos para el proximo modulo!
